### ISSUE TITLE
Prepare final Cohort Call [ 2024-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/cohort-planning#11]
- [x] Create Agenda (kyber)
- [x] Invite participants / teams to sign up in Agenda to present their Pathway
- [x] create Survey - copy most recent and save; in OpenscapesMain > OpenscapesMetrics > Surveys @stefaniebutland could you please create the survey?
  - [x] Add link to Agenda
- [x] Review roles and timing

**Comment by stefaniebutland** [comment]
33 Certificates uploaded to Cohort Folder. did one spot check. @jules32 please check

**Comment by jules32** [comment]
looks great, thank you!

**Comment by stefaniebutland** [comment]
completed!
