### ISSUE TITLE
Summary blog post [ 2024-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/cohort-planning#17]
- [x] select one project or pathway element from each team
- [x] draft post
- [x] publish & skeet / toot post

**Comment by jules32** [comment]
Blog post mostly drafted in early June: https://docs.google.com/document/d/1nJeihvCIfkKJ8hA2TiUAY4-i2y6evq9PyZYTe6Wo2Nw/edit#heading=h.oxo31fk238cj. I will review this morning and discuss with Mentors Wednesday

**Comment by jules32** [comment]
I've reviewed and made further edits. The only part left is to share what we learned based on Mentors' feedback, which we'll hear on Wednesday mentors call

**Comment by stefaniebutland** [comment]
published https://nasa-openscapes.github.io/news/2024-07-24-2024-nasa-champions-cohort/

closed as completed
