### ISSUE TITLE
02 Cohort tech setup [ 2024-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/cohort-planning#2]
## For Cohort Planning Team (Stef, Julie)

These tasks are described in the [Approach Guide - Cohort tech setup](https://openscapes.github.io/approach-guide/champions/pre-cohort-tech.html)

- [x] invite co-leads/assists to Google Calendar Cohort Calls and optional Coworking sessions via OpenscapesEvents Calendar
  - Approach Guide has sample text for invite titles and descriptions

GitHub:
-   [x] create GitHub repo for cohort with cohort name (example: github.com/openscapes/2022-noaa-sefsc-summer)
-   [x] Write Cohort info on the README (kyber)
-   [x] Add our Code of Conduct (kyber)
-   [x] add Google Folder link (created below) to README
-   [x] Make it a website: Settings \> Pages \> Branch: main, dir: root; add website link to repo About
-   [x] Invite co-leads/assists to GitHub repo with Maintainer permissions

Google Folder:
-   [x] create Google Folder for participants (example: `Openscapes_CohortCalls [ 2022-noaa-sefsc-summer ]`)
-   [x] add co-leads/assists to that Google Folder

**Comment by stefaniebutland** [comment]
https://github.com/NASA-Openscapes/2024-nasa-champions

https://nasa-openscapes.github.io/2024-nasa-champions/

**Comment by jules32** [comment]
✅  Updated README with updated Calendaring and Teaching Leads

**Comment by stefaniebutland** [comment]
Copied template doc for DebriefsDigests to NASA-ChampionsCohort-Planning
