### ISSUE TITLE
03 Participants setup & welcome [ 2024-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/cohort-planning#3]
## Adding Participants (giving access at the right time)

Data entry:
-   [ ] Add Participants to database: : OpenscapesParticipantsMainList and OpenscapesParticipants [ year-chort-name ]

Emails
-   [x] send welcome email (see [Approach Guide - Cohort welcome](https://openscapes.github.io/approach-guide/champions/pre-cohort-engage.html#cohort-welcome) for examples)
-   [x] day before Call 1, send "reminder", after adding participants to `Openscapes_CohortCalls` folder

Google Calendar:
-   [x] when sending Welcome Email, add participants emails to Google Calendar Invites: OpenscapesEvents for Cohort Calls and optional Coworking sessions.
  - [Approach Guide - Pre-cohort engagement](https://openscapes.github.io/approach-guide/champions/pre-cohort-engage.html) has sample text for invite titles and descriptions

Google Folder:
-   [x] day before Call 1, add participants emails to `Openscapes_CohortCalls` folder
-   [x] add  Google Folder link to Google Calendar recurring invite under description

**Comment by jules32** [comment]
Status update: 7 teams nominated! We've sent acceptance emails and have heard from 6 of the teams so far. They have been added to the 5 Cohort Calls calendars and have booked 1:1s.

**Comment by jules32** [comment]
- [x] Julie will send final email above and add people to Google Folder on April 1

**Comment by jules32** [comment]
@stefaniebutland , I wonder if the very first checkbox above

> Data entry: Add Participants to database: : OpenscapesParticipantsMainList and OpenscapesParticipants [ year-chort-name ]

should actually go at the end, during cohort wrap-up. That way we have their github usernames and any gmail address they've added. If you agree, would you be able to make that change to the issue template & approach guide, and we'll close this issue?

**Comment by stefaniebutland** [comment]
I moved Participants List task to Wrap Up issue template for Opencapes and NASA-Openscapes cohort-planning.

closing this issue as complete
