### ISSUE TITLE
Call 1 Digest & additional setup [ 2024-nasa-champions ]

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/cohort-planning#6]
- [x] Debrief Notes

- [x] Digest 1, via email (include Slack invite & orientation, below), then post as issue in Cohort repo
  - [examples in Approach Guide](https://openscapes.github.io/approach-guide/champions/leading-cohort-calls.html#between-cohort-calls)

Slack
-   [x] create private cohort channel 
-   [x] Email participants link to join Slack, with orientation to Slack e.g. how to, #welcome channel, etc 

Google Calendar
-   [ ] add participants emails to Google Calendar Invites for Coworking times (participation optional)

**Comment by stefaniebutland** [comment]
Created Slack private #2024-nasa-champions with description. Did not send invitations

**Comment by jules32** [comment]
Stef sent invitations on Apr 16
